{
 "title": "System Health Dashboard",
 "tags": [
  "fraud",
  "system",
  "api"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(fraud_api_requests_total[1m])",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "API p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(fraud_api_request_latency_seconds_bucket[5m]))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(fraud_api_requests_total{status=\"500\"}[5m])",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory %"
    }
   ]
  }
 ]
}